### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by vinyll** [enac-bienetre/enac#2]
- [x] créer un logo (une typo suffit)
- [x] améliorer la présentation d'accueil (menu clair / informations générales lisibles)
- [x] améliorer la présentation des pages "pratiques" (lisibilité)
- [x] intégrer everywhere.js pour l'édition
- [x] responsive
- [x] ajouter le Vitruvian Man (thème)
- [x] sticky du header
- [x] fichier d'explication des métas
- [x] intégrer les contenus fournis
